# Generated by Django 5.0.7 on 2024-10-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_order_product_id_order_product_type_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
