# Generated by Django 5.0.7 on 2024-10-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='description',
        ),
    ]
